version: '3.9'

services:
    db:
        image: postgres:16-alpine
        restart: unless-stopped
        environment:
            POSTGRES_USER: b5chat
            POSTGRES_PASSWORD: my-secret-token
            POSTGRES_DB: b5chat
        volumes:
            - db_data:/var/lib/postgresql/data
        ports: ['4000:5432']

    # FIXME: Fix docker composer so it hosts everything properly.
    # api:
    #     build:
    #         context: ..
    #         dockerfile: apps/api/Dockerfile
    #         target: dev
    #     depends_on: [db]
    #     environment:
    #         DATABASE_URL: postgres://b5chat:my-secret-token@db:4000/b5chat
    #         PORT: 3001
    #     volumes:
    #         - ..:/src
    #         - bun-api-cache:/root/.bun
    #     ports: ['3001:3001']

    # web:
    #     build:
    #         context: ..
    #         dockerfile: apps/web/Dockerfile
    #         target: dev
    #     depends_on: [api]
    #     environment:
    #         VITE_API_URL: http://api:3001
    #     volumes:
    #         - ..:/src
    #         - bun-web-cache:/root/.bun
    #     ports: ['5173:5173']

volumes:
    db_data:
    bun-api-cache:
    bun-web-cache:
